-- CHAVE PRIMARIA DAS TABLEAS
ALTER TABLE `produto` MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `categoria` MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `sub_categoria` MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `produto_foto` MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `produto_click` MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `pedidos_itens` MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `pedidos` MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `marca` MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `lista_desejo` MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `fornecedor` MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `empresa` MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `cliente` MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `cidade` MODIFY COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY;
-- ALTERAÇÃO ESTRUTUDA EMPRESA
ALTER TABLE `empresa` DROP COLUMN `cidade_id`;
ALTER TABLE `empresa` ADD COLUMN `cidade` VARCHAR(50) DEFAULT NULL;
-- PEDIDOS CABEÇA
ALTER TABLE `pedidos` ADD COLUMN `datac` DATE DEFAULT NULL;
ALTER TABLE `pedidos` ADD COLUMN `codcli` INTEGER DEFAULT NULL;
ALTER TABLE `pedidos` ADD COLUMN `chave` CHAR(26) DEFAULT NULL;
ALTER TABLE `pedidos` CHANGE COLUMN `codcli` `cliente_id` INTEGER(11) DEFAULT NULL;
ALTER TABLE `pedidos` ADD COLUMN `cupom_id` INTEGER DEFAULT NULL;
ALTER TABLE `pedidos` ADD COLUMN `total_produtos` FLOAT(9,2) DEFAULT NULL;
ALTER TABLE `pedidos` ADD COLUMN `desconto` FLOAT(9,2) DEFAULT NULL;
ALTER TABLE `pedidos` ADD COLUMN `total_pedido` FLOAT(9,2) DEFAULT NULL;
-- PEDIDOS ITENS
ALTER TABLE `pedidos_itens` ADD COLUMN `chave` CHAR(26) DEFAULT NULL;
ALTER TABLE `pedidos_itens` ADD COLUMN `produto_id` INTEGER DEFAULT NULL;
ALTER TABLE `pedidos_itens` ADD COLUMN `valor_unitario` DECIMAL(11,2) DEFAULT NULL;
ALTER TABLE `pedidos_itens` ADD COLUMN `valor_unitario` FLOAT(9,2) DEFAULT NULL;
ALTER TABLE `pedidos_itens` ADD COLUMN `qtde` FLOAT(9,2) DEFAULT NULL;
ALTER TABLE `pedidos_itens` ADD COLUMN `desconto_unitario` FLOAT(9,2) DEFAULT NULL;
ALTER TABLE `pedidos_itens` ADD COLUMN `datac` DATE DEFAULT NULL;
--CUPOM DE DESCONTO
CREATE TABLE `cupom_desconto` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `cupom` VARCHAR(20) DEFAULT NULL,
  `data_ini` DATE DEFAULT NULL,
  `data_fim` DATE DEFAULT NULL,
  `valor` FLOAT(9,2) DEFAULT NULL,
  `tipo_desconto` CHAR DEFAULT NULL COMMENT 'P=>percentual\r\nV=>valor',
  `hora_ini` TIME DEFAULT '00:00:00',
  `hora_fim` TIME DEFAULT '00:00:00',
  `descricao` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ;

ALTER TABLE `pedidos_itens` ADD COLUMN `nome_produto` VARCHAR(50) DEFAULT NULL;

ALTER TABLE `pedidos` ADD COLUMN `cupom_desconto_id` INTEGER DEFAULT NULL;
ALTER TABLE `cupom_desconto` ADD COLUMN `qtde` INTEGER DEFAULT NULL;
ALTER TABLE `pedidos_itens` ADD COLUMN `nro_item` INTEGER DEFAULT NULL;